					<address>
					  <!-- <strong>Murphy's Salem</strong><br> -->
					  300 Derby St<br>
					  Salem, MA 01970<br>
					  Phone: 978-744-8889 <br />
					  <!-- Hours: Every Day: 11:30am-1am<br /> -->
					  Email : <a href="mailto:info@murphyspubsalem.com">info@murphyspubsalem.com</a> <br />
					  <!-- Facebook : <a target="_blank" href="http://facebook.com/pages/Murphys-Restaurant-Pub/637938886216768">facebook.com</a> <br /> -->
					</address>
