					<address>
					  <strong>Murphy's Salem</strong><br>
					  300 Derby St<br>
					  Salem, MA 01970<br>
					  Phone: 978-744-8889 <br />
					  Hours: Every Day: 11am-1am<br /><br />
					  Email : <a href="#">info@murphyspubsalem.com</a> <br />
					  Facebook : <a target="_blank" href="http://facebook.com/pages/Murphys-Restaurant-Pub/637938886216768">facebook.com</a> <br />
					</address>